spring:
  profiles:
    group:
      local: common, domain
      prod: common, domain
    include:
      - infra

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  swagger-ui:
    persist-authorization: true
    default-models-expand-depth: -1

server:
  shutdown: graceful

jwt:
  access-token:
    header: Access-token
  refresh-token:
    header: Refresh-token
---
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_API_KEY}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret-key: ${SECRET_KEY}
  access-token:
    expiration: 2592000 #3일
