spring:
  profiles:
    group:
      local: common, domain, infra
      dev: common, domain, infra

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  swagger-ui:
    persist-authorization: true
    default-models-expand-depth: -1

server:
  shutdown: graceful

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    header: Access-token
  refresh-token:
    header: Refresh-token
---
spring:
  config:
    activate:
      on-profile: local
jwt:
  access-token:
    expiration: 2592000 #3일

---
spring:
  config:
    activate:
      on-profile: dev
jwt:
  access-token:
    expiration: 2592000 #3일
