spring:
  profiles:
    group:
      local: common, domain
      prod: common, domain
    include:
      - infra

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  swagger-ui:
    persist-authorization: true
    default-models-expand-depth: -1

server:
  shutdown: graceful

jwt:
  access-token:
    header: Access-token
  refresh-token:
    header: Refresh-token
---

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    expiration: 2592000 #3일
